# This is a basic workflow to help you get started with Actions

name: output

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  output:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Show output
        run: echo "${{ toJSON(github) }}"

  output2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: output
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Show output
        run: echo "${{ toJSON(github) }}"
